# Generated by Django 6.1 on 2026-08-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(blank=True, choices=[('cocktail', 'Coquetel'), ('beer', 'Cerveja'), ('wine', 'Vinho'), ('spirit', 'Destilado'), ('other', 'Outro')], max_length=20)),
                ('fallback_photo_url', models.URLField(blank=True, help_text='Foto padrão usada quando um check-in não tem foto própria.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
