# Generated by Django 6.1 on 2026-08-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='checkins/'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Usada quando a foto vem de uma busca automática (web) em vez de upload direto.'),
        ),
    ]
