# Generated by Django 6.1 on 2026-08-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_checkin_photo_alter_checkin_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Foto escolhida pelo usuário como capa deste drink no catálogo. Único por (user, drink) — reforçado em CheckInViewSet.set_cover.'),
        ),
    ]
