# Generated by Django 6.1 on 2026-08-20 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-created_at']},
        ),
    ]
